; Auto-generated. Do not edit!


(cl:in-package basics-msg)


;//! \htmlinclude TalkGoal.msg.html

(cl:defclass <TalkGoal> (roslisp-msg-protocol:ros-message)
  ((sentence
    :reader sentence
    :initarg :sentence
    :type cl:string
    :initform ""))
)

(cl:defclass TalkGoal (<TalkGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TalkGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TalkGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name basics-msg:<TalkGoal> is deprecated: use basics-msg:TalkGoal instead.")))

(cl:ensure-generic-function 'sentence-val :lambda-list '(m))
(cl:defmethod sentence-val ((m <TalkGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader basics-msg:sentence-val is deprecated.  Use basics-msg:sentence instead.")
  (sentence m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TalkGoal>) ostream)
  "Serializes a message object of type '<TalkGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'sentence))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'sentence))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TalkGoal>) istream)
  "Deserializes a message object of type '<TalkGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'sentence) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'sentence) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TalkGoal>)))
  "Returns string type for a message object of type '<TalkGoal>"
  "basics/TalkGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TalkGoal)))
  "Returns string type for a message object of type 'TalkGoal"
  "basics/TalkGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TalkGoal>)))
  "Returns md5sum for a message object of type '<TalkGoal>"
  "3ee8e7a1b3ec1e5b34263db750df6246")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TalkGoal)))
  "Returns md5sum for a message object of type 'TalkGoal"
  "3ee8e7a1b3ec1e5b34263db750df6246")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TalkGoal>)))
  "Returns full string definition for message of type '<TalkGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# The sentence to be spoken~%string sentence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TalkGoal)))
  "Returns full string definition for message of type 'TalkGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# The sentence to be spoken~%string sentence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TalkGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'sentence))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TalkGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TalkGoal
    (cl:cons ':sentence (sentence msg))
))
