; Auto-generated. Do not edit!


(cl:in-package basics-msg)


;//! \htmlinclude TalkResult.msg.html

(cl:defclass <TalkResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TalkResult (<TalkResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TalkResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TalkResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name basics-msg:<TalkResult> is deprecated: use basics-msg:TalkResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TalkResult>) ostream)
  "Serializes a message object of type '<TalkResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TalkResult>) istream)
  "Deserializes a message object of type '<TalkResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TalkResult>)))
  "Returns string type for a message object of type '<TalkResult>"
  "basics/TalkResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TalkResult)))
  "Returns string type for a message object of type 'TalkResult"
  "basics/TalkResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TalkResult>)))
  "Returns md5sum for a message object of type '<TalkResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TalkResult)))
  "Returns md5sum for a message object of type 'TalkResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TalkResult>)))
  "Returns full string definition for message of type '<TalkResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# No result content needed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TalkResult)))
  "Returns full string definition for message of type 'TalkResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# No result content needed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TalkResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TalkResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TalkResult
))
